### ISSUE TITLE
Multi-line comment

### ISSUE THREAD

**Issue by mpancorbo** [ruivieira/latex-friend#10]
Hi, thanks for your useful package.

I'd love to see a multi-line comment feature. I've found it in simpler editors (say, `gedit`) but I can't do it in Atom.

TIA

**Comment by ruivieira** [comment]
@mpancorbo thank you.

By multi-line comments do you mean the ability to comment out multiple lines simultaneously?

If so, the [language-latex](https://atom.io/packages/language-latex) package provides this and I try not to duplicate features from this package.

**Comment by mpancorbo** [comment]
Jeppp... you're right! I simply missed this option in language-latex.

You can close the issue. Thanks!

**Comment by ruivieira** [comment]
No problem.
